nuita/panchira

lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/resolver.rb

Set User Agent

---

lib/panchira.rb
lib/panchira/extensions.rb
lib/panchira/resolvers/resolver.rb

Add simple documentation

---

lib/panchira/extensions.rb
lib/panchira/resolvers/resolver.rb

ダックタイピング最高！ドキュメンテーション用のコメントちょっと修正した
他の部分も英語とか内容とか変なところあったらどんどん治していきたい

fix documentations

---

test/panchira_test.rb

なんかInstagramは未ログイン状態だとログインページに飛ばされたりする？ので、単純なテストには適してなさそう

remove Instagram from testdata

---

lib/panchira/resolvers/narou_resolver.rb
test/resolvers/narou_test.rb

resolve https://github.com/nuita/panchira/issues/15
novel18のタグを取得するのを実装するついでにncodeのほうでも取得できるようにしました。

なろうのタグを取得します。

---

test/resolvers/melonbooks_test.rb

こういう変更頻繁にありそうだからタグに対するテスト緩くしてもいいかも

melonbooks_testのタグを修正

---

Gemfile.lock
README.md
lib/panchira/version.rb

READMEとかドキュメントを更新する必要があるけど、タグの取得も揃ったところで機能的にはv1.0って呼んでいいものができたんじゃないかなーと思います。
できたよね？というかみんなどうやってバージョン番号つけてるんだ……？

Release v1.0.0

---

test/resolvers/dlsite_test.rb
test/resolvers/komiflo_test.rb
test/resolvers/melonbooks_test.rb
test/resolvers/narou_test.rb
test/resolvers/nijie_test.rb
test/resolvers/pixiv_test.rb

タグが元サイトで変更されるたびにテスト落ちるのあれな気がしたので……

タグのテストをゆるくした

---

lib/panchira/resolvers/fanza_resolver.rb
lib/panchira/resolvers/resolver.rb
test/resolvers/fanza_test.rb

- book.dmm.co.jp 対応
- Resolver::fetch_pageでクッキーを指定できるようになった
- ~~子クラスで定数COOKIEを指定すると動くよ~~
- Resolver#cookie() に機能うつしました

Fanza Resolver

---

lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/pixiv_resolver.rb
lib/panchira/resolvers/resolver.rb

UA参照するときに Resolver.user_agent() 見るようにした

UAもメソッドで指定したほうが柔軟でよさそう

---

Gemfile.lock

release 1.1.0

---

.github/workflows/ruby.yml

cf: https://github.com/nuita/nuita/pull/281/commits/2565ed4d5101fd222ba1ab7369993c7fb015fe66

動かなくなってたGithub Actionsを修正

---

CHANGELOG.md
lib/panchira/version.rb

- Added support for Fanza Video.

release 1.3.1

---

lib/panchira/resolvers/iwara_resolver.rb
test/resolvers/iwara_test.rb

descriptionのparseは、テストに使っていた動画にdescが無いということに後で気付いたので実装されていません……。

implement iwara resolver

---

CHANGELOG.md
Gemfile.lock
README.md
lib/panchira/version.rb

- Added Support for Iwara.
- Fixed an issue where DLsite Resolver was retrieving wrong tags.

Release 1.3.3

---

lib/panchira/resolvers/iwara_resolver.rb
test/resolvers/iwara_test.rb

before
```
irb(main):001:0> Panchira.fetch "https://ecchi.iwara.tv/videos/3do1kceoeji4azl5a"
=> #<Panchira::PanchiraResult:0x00007fa606340680 @canonical_url="https://ecchi.iwara.tv/videos/3do1kceoeji4azl5a", @title="北上〇葉ちゃんのおっぱいを楽しむふっきれた！", @description="", @image=#<Panchira::PanchiraImage:0x00007fa60688dac0 @url="https://i.iwara.tv/sites/default/files/videos/thumbnails/1319221/thumbnail-1319221_0012.jpg", @width=2560, @height=1440>, @tags=["youtubeに規制されまくって怒りがたまったので北〇双葉ちゃんに脱いでもらいました\nよろしくお願いしますm(__)m\nお借りしたもの\n・ktkmftb  ymtior   .  l  i  v  e\n・おっぱい吹っ切れたBBver　Ngon\n・ごうかなカジノ　Cyalon\n・raymmd Rui\n・ikboke ikeno\n・ポストポイントライト　ビームマンP\n・ AutoLuminous Ver.3.6  そぼろ\n・M4Layer　ミーフォ茜\n・WorkingFloor2.fx ver0.0.8　針金P\n・空中に漂う埃エフェクト　化身バレッタ\ndol部のエッチな作品もっと増えないかな～\nみんなもつくってくれ～！頼む～\nyoutubeでも動画上げてるから見にきてね！\ …
```

iwaraのdescriptionが存在する動画について、tagに混ざっていたのを修正

---

test/resolvers/narou_test.rb

(https://twitter.com/girls_narou/status/1421064512438902794 こちらに元の作品は引っ越しました)

テストに使っていた作品が消えたので、別の作品に変える。

---

lib/panchira/resolvers/pixiv_resolver.rb
test/resolvers/pixiv_test.rb

Add pixiv novel resolver

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- Added support for Pixiv Novel.
- Fixed an issue where Image Resolver missed image scales.

release v1.3.5

---

.rubocop.yml
lib/panchira/resolvers/dlsite_resolver.rb
lib/panchira/resolvers/fanza_resolver.rb
lib/panchira/resolvers/iwara_resolver.rb
lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/melonbooks_resolver.rb
lib/panchira/resolvers/narou_resolver.rb
lib/panchira/resolvers/nijie_resolver.rb
lib/panchira/resolvers/pixiv_resolver.rb
lib/panchira/resolvers/resolver.rb
lib/panchira/resolvers/twitter_resolver.rb
panchira.gemspec
test/resolvers/dlsite_test.rb
test/resolvers/pixiv_test.rb
test/resolvers/twitter_test.rb

数ヶ月放置してたら最新のページに対応できなくなっていたので諸々更新しました。
- MelonbooksResolver
- FanzaBooksResolver
- DLSiteResolver で ja 以外のlocaleが指定されていた場合に取得失敗する問題を修正
- 最新のRubocopに対応するためコードスタイルを修正

諸々のResolverを最新化
