lib/panchira.rb
lib/panchira/extensions.rb
lib/panchira/resolvers/dlsite_resolver.rb
lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/melonbooks_resolver.rb
lib/panchira/resolvers/narou_resolver.rb
lib/panchira/resolvers/nijie_resolver.rb
lib/panchira/resolvers/pixiv_resolver.rb
lib/panchira/resolvers/resolver.rb

- Resolverの一覧をPanchira::Extensions::resolversで管理
- Panchira::Extensions.register(Panchira::***Resolver) でResolverを登録できる
- Resolverの適用条件はResolver::URL_REGEXPとのマッチにまとめられた

各Resolverの一覧をpanchira/extensionsで管理

---

lib/panchira.rb
lib/panchira/panchira_result.rb
lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/resolver.rb
test/panchira_test.rb
test/resolvers/dlsite_test.rb
test/resolvers/komiflo_test.rb
test/resolvers/melonbooks_test.rb
test/resolvers/narou_test.rb
test/resolvers/nijie_test.rb
test/resolvers/pixiv_test.rb

close #4 
- 取得したページを表す `PanchiraResult`, 取得した画像（URL, 大きさ）を表す `PanchiraImage` クラスを作成
- 全部attr_accessorつけてオープンに使う
- `Panchira#fetch` の返り値は `PanchiraResult` を返す
- 既存テストをこの仕様に合わせて変更

Panchira#fetchの返り値をハッシュからクラスに変更

---

lib/panchira/resolvers/resolver.rb

link rel=canonical で取得したページがまた別のcanonical指定してるみたいな状況でも上手にやる

fetch_canonical_url修正、既知のURLが出てくるまでループ回す

---

lib/panchira/resolvers/resolver.rb
lib/panchira/resolvers/twitter_resolver.rb
test/resolvers/twitter_test.rb

twitter liteが全体に出るようになって、普通のUAだと `og:image` とかつかなくなったので、 [Facebookクローラー](https://developers.facebook.com/docs/sharing/webmasters/crawler)を名乗ります。

add twitter resolver

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- You can now register and use your own Resolver with this gem. (see Panchira::Extensions#register)
- Added support for new Twitter UI.
- Panchira::fetch now returns an instance of PanchiraResult instead of a hash.
- Changed default User-Agent slightly.

Release v0.3.0

---

CHANGELOG.md
README.md
lib/panchira/version.rb

- Added support for Fanza Books.
- Added support for direct links to an image.
- You can now set cookie by overriding Resolver#cookie in individual resolvers.
- Resolver::USER_AGENT changed to Resolver#user_agent.

Release 1.1.0

---

lib/panchira/resolvers/fanza_resolver.rb
test/resolvers/fanza_test.rb

うっかり`parse_image_url`の代わりに`parse_image`をオーバーライドしてました。
テストのほうも間違えてたから気づかなかった、こわい……

FANZA書籍の画像取得処理を修正

---

lib/panchira/resolvers/fanza_resolver.rb
test/resolvers/fanza_test.rb

FANZAのクッションページは全部同じcookieで乗り切れる感じがしてきたので、とりあえずFanzaResolverにその処理は共有化した。
ページの仕組みはけっこう違いそうなので、よく使われそうなサービスに対しては別々のResolver作りました。それぞれFanzaResolverを継承します。
呼び出し順が分からない関係でこれ自体を登録できないのがけっこう困るので、呼び出す順番を管理する仕組みが必要かもしれない

FANZA同人resolver

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

ほぼ不完全だったFanzaResolverの修正だから、厳密にはバグフィックスだけじゃないけど1.1.1ってしちゃいます
- Added support for Fanza Doujin.
- Added support for description in Fanza Book.
- Fixed an issue that fetching image was not working in Fanza Book.

release 1.1.1

---

lib/panchira/panchira_result.rb
lib/panchira/resolvers/dlsite_resolver.rb
lib/panchira/resolvers/fanza_resolver.rb
lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/melonbooks_resolver.rb
lib/panchira/resolvers/narou_resolver.rb
lib/panchira/resolvers/nijie_resolver.rb
lib/panchira/resolvers/pixiv_resolver.rb
lib/panchira/resolvers/resolver.rb
test/panchira_test.rb
test/resolvers/dlsite_test.rb
test/resolvers/fanza_test.rb
test/resolvers/komiflo_test.rb
test/resolvers/melonbooks_test.rb
test/resolvers/narou_test.rb
test/resolvers/nijie_test.rb
test/resolvers/pixiv_test.rb

著者名とかサークル名を取得できるようにしました。思ったよりmetaタグに書いてくれてるサイトなくて巨大PRになってしまった……。
タイトルに著者名が含まれてるサイトとかも多いので、それを解析する過程でタイトル自体の値も変わっているものがあります。

著者名、サークル名を取得できるようにする

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- You can now fetch author and circle name in resolvers (Resolver#fetch_author, Resolver#fetch_circle).
- Resolver#fetch_title returns the title of the content (not the original title of the page).

release 1.2.0

---

.rubocop.yml
lib/panchira/panchira_result.rb
lib/panchira/resolvers/image_resolver.rb
lib/panchira/resolvers/melonbooks_resolver.rb
lib/panchira/resolvers/resolver.rb
test/panchira_test.rb
test/resolvers/dlsite_test.rb
test/resolvers/komiflo_test.rb
test/resolvers/melonbooks_test.rb
test/resolvers/nijie_test.rb
test/resolvers/pixiv_test.rb

- `PanchiraResult#resolver` を追加
- `Resolver#fetch_resolver()` を追加
https://github.com/nuita/nuita/issues/314
生の`self.class`を渡すと面倒くさそうなので文字列に変換してますが、用途があれば変換せずに渡したほうがいいのかもしれない（思いつかず）

取得したResolverの名前をPanchiraResultに追加

---

lib/panchira/panchira_result.rb
lib/panchira/resolvers/dlsite_resolver.rb
lib/panchira/resolvers/resolver.rb
test/resolvers/dlsite_test.rb

複数の作者を保存するために、`PanchiraResult#author`を削除し、代わりに`PanchiraResult#authors`を追加しました。
従来のコードをそのまま使えるように、以下の変更を加えてあります。
- `PanchiraResult#author()`, `PanchiraResult#author=()` を実装
- `authors`の値を素の文字列としてget, setできます(setterでは空白文字は配列にsplitされます)。
- `Resolver#fetch()`内で`parse_authors()` から値を取得できるようにする
- `parse_authors()`が実装されているResolverでは、`parse_author()`を呼び出しません。
- `parse_authors()`が実装されていないResolverに対しては、これまで通り`parse_author()`を見ます。
- `Panchira::Resolver`自体には`parse_authors()`は定義されていないので、子クラスで独自に定義しなければ従来どおりの`parse_author()`が呼ばれることになります。

複数著者を配列として取れるようになる

---

CHANGELOG.md
Gemfile.lock
README.md
lib/panchira/version.rb

- Added support for multiple authors. PanchiraResult#authors now returns an array of authors.
- PanchiraResult now returns a resolver name used in the process (PanchiraResult#resolver).
- Fixed an issue that fetching DLSite pages with multiple authors were not working.
- Fixed a slight issue in MelonbooksResolver.

Release 1.3.0

---

lib/panchira/resolvers/fanza_resolver.rb
test/resolvers/fanza_test.rb

close #46 
FANZA同人のCG作品でcanonical_urlに別サービス(FANZA GAMES)のurlが入っていることがあるので、一旦デフォルトで行っているURLの正規化をやめました。共有ボタンとか色々試した感じ、現状では特に問題起こらなさそうですが、そのうち手でこっちが正規化してあげる必要があるかも？

FANZA同人のcanonical urlを一旦無効にする

---

lib/panchira/resolvers/narou_resolver.rb

なろうのog:descriptionがタグ名をjoinしたものを返すようになっていたので、descriptionもテーブルからあらすじの列を取得するようにしました。
1つのテーブルから複数の項目(author, description, tags...)を取得する場合、テーブルの列ごとにeach回して見出しの内容に応じて一気に取得したほうが柔軟な設計になりそう。なので、個別Resolverのメソッドからまとめて@authorとか@description代入できるようにして、本筋のResolverではその後に@authorがnilだったらparse_author呼ぶ、みたいな設計にしたほうが柔軟性が上がって良い気がする。

narou_resolverのdescriptionをテーブル内から指定

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- Fixed an issue where Fanza Resolver was retrieving incorrect cannonical URLs.
- Fixed an issue where Narou Resolver was retrieving wrong descriptions.
- Updated dependencies.

release 1.3.2

---

lib/panchira/resolvers/dlsite_resolver.rb
lib/panchira/resolvers/narou_resolver.rb
lib/panchira/resolvers/resolver.rb

DOMの構造が変わったのか、いままで識別に使っていたクラスが他の要素にも貼られるようになってたので、
authorと同じようにテーブルの中身を1行ずつ読むスタイルに変更しました（非効率なのでどうにかしたい）。
あと、リダイレクトが必要なテストケースでカノニカルURLが`og:url`だけで提供されてて認識できてなかったので、`Panchira::Resolver#fetch_canonical_url`もちょっと変更しました（もしかしたら他のテストケース壊れるかも？）。

DLSiteの取得が失敗する問題を修正

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- Fixed an issue where Iwara Resolver failed when a description was present.

release 1.3.4

---

lib/panchira/resolvers/melonbooks_resolver.rb
test/resolvers/melonbooks_test.rb

Melonbooks Resolverでwidthの制限が残っていたので、imageクエリだけ残してほかはすべて削除する実装に変更しました。

Melonbooks Resolverでwidth制限なしの画像を取得する

---

.github/workflows/ruby.yml
.rubocop.yml
panchira.gemspec

2.6は今年3月にEOLらしいので、とりあえず対応バージョンを2.7以上にしました。
あと、CIを修正して複数バージョンでテストが回るようにしました。

Rubyの最低対応バージョンを2.7に上げる

---

lib/panchira/resolvers/nijie_resolver.rb
test/resolvers/nijie_test.rb

nijie resolverでjsonパースせずに無理やり正規表現で画像のurlを抽出してましたが、url形式に変更が入ったらしく、これを機会にjsonをちゃんとパースするように変更しました。

Nijie resolverのparse_imageのロジックを変更

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- Added support for non-Japanese pixiv URLs.
- Fixed an issue where Nijie Resolver failed to fetch image.
- Dropped support for Ruby 2.6.

Release v1.4.0

---

.github/workflows/ruby.yml
.rubocop.yml
lib/panchira.rb
lib/panchira/resolvers/komiflo_resolver.rb
lib/panchira/resolvers/narou_resolver.rb
lib/panchira/resolvers/pixiv_resolver.rb
lib/panchira/resolvers/resolver.rb
lib/panchira/resolvers/twitter_resolver.rb
test/resolvers/nijie_test.rb
test/resolvers/twitter_test.rb

センシティブ設定されているアカウントに対して、個別ツイートを取得しようとすると301でプロフィールに飛ばされたり、og:imageが取得できなかったりするので、抜本対応として公式APIを使用します。
レートリミットが15分で900回なので、将来的にもっといい感じにする対応が必要かも。
```ruby
Panchira.fetch('https://twitter.com/hogehoge/12345678', {twitter: {bearer_token: "XXXXXX"}})
```
また、APIを使用する自動テストは環境変数 `TWITTER_BEARER_TOKEN` が設定されている場合のみ有効になります。この対応として、Github Actions上に変数を追加する修正も入っています。

Twitterの解析に公式APIを使用する

---

lib/panchira/resolvers/twitter_resolver.rb
test/resolvers/nijie_test.rb
test/resolvers/twitter_test.rb

TwitterのURL構造が変わってparse_authorで落ちるようになっていたので、一旦author切り取れなくても落ちないように例外処理を追加しました。
将来的にTwitter API使って取得する形にしてもいいかもしれない。

TwitterのURL構造変わってたので緊急対応

---

lib/panchira/resolvers/resolver.rb

デフォルトのタイムアウトが60秒と長すぎるので、デフォルトのresolverにだけタイムアウト値を設定しました。一旦10秒で

タイムアウトを10秒に設定

---

lib/panchira/resolvers/pixiv_resolver.rb
test/resolvers/pixiv_test.rb

pixiv.cat のレートリミットに引っかかることが増えてきたため、オリジナルのURIを返せるようにしました。
ただし、返却されたURIを使用するためにはリクエストのRefererの設定が必要なので、デフォルトではpixiv.catを使うままの設定にしてあります。
```ruby
irb(main):001:0> Panchira.fetch "https://www.pixiv.net/artworks/96792681", {pixiv: {fetch_raw_image_url: true}}
=> #<Panchira::PanchiraResult:0x00007f98473037c0 @canonical_url="https://pixiv.net/member_illust.php?mode=medium&illust_id=96792681", @title="盛り盛りYMD", @description="Lカップと聞いて", @image=#<Panchira::PanchiraImage:0x00007f98472b2028 @url="https://i.pximg.net/img-original/img/2022/03/09/19/46/19/96792681_p0.png", @width=nil, @height=nil>, @tags=["R-18", "ラプラス・ダークネス", "hololive", "ホロライブ", "パイズリ希望", "バーチャルYouTuber", "マイクロビキニ", "巨乳", "ロリ爆乳"], @authors=["atahuta"], @circle=nil, @resolver="Panchira::PixivResolver">
```

pixiv.cat 介さないURIを返せるようにする

---

CHANGELOG.md
Gemfile.lock
README.md
lib/panchira/version.rb

- Pixiv resolver can now fetch image URIs that are not proxied.

Release 1.5.1

---

lib/panchira/resolvers/pixiv_resolver.rb
test/resolvers/pixiv_test.rb

Pixiv Resolverの生URI取得時にscaleを取得

---

CHANGELOG.md
Gemfile.lock
lib/panchira/version.rb

- Fixed an issue where Pixiv resolver can't retrieve not-proxied image scales.

release 1.5.2
